wandb_version: 1

activation:
  value: tanh
augment:
  value: true
batch_size:
  value: 32
batchnorm:
  value: false
conv_filters:
  value:
  - 32
  - 64
  - 128
  - 128
  - 128
dense_neurons:
  value: 256
dropout:
  value: 0.3
kernel_sizes:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
lr:
  value: 0.0005
max_epochs:
  value: 15
project:
  value: assignment_2
