wandb_version: 1

activation:
  value: tanh
augment:
  value: true
batch_size:
  value: 64
batchnorm:
  value: true
conv_filters:
  value:
  - 64
  - 64
  - 64
  - 64
  - 64
dense_neurons:
  value: 128
dropout:
  value: 0.5
kernel_sizes:
  value:
  - 5
  - 3
  - 3
  - 3
  - 3
lr:
  value: 0.001
max_epochs:
  value: 15
project:
  value: assignment_2
