wandb_version: 1

activation:
  value: relu
augment:
  value: false
batch_size:
  value: 64
batchnorm:
  value: false
conv_filters:
  value:
  - 64
  - 128
  - 256
  - 256
  - 256
dense_neurons:
  value: 256
dropout:
  value: 0.5
kernel_sizes:
  value:
  - 5
  - 3
  - 3
  - 3
  - 3
lr:
  value: 0.001
max_epochs:
  value: 15
project:
  value: assignment_2
