wandb_version: 1

activation:
  value: relu
augment:
  value: true
batch_size:
  value: 32
batchnorm:
  value: true
conv_filters:
  value:
  - 64
  - 128
  - 256
  - 256
  - 256
dense_neurons:
  value: 256
dropout:
  value: 0.5
kernel_sizes:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
lr:
  value: 0.0005
max_epochs:
  value: 15
project:
  value: assignment_2
